### ISSUE TITLE
choice_expression as actionable_expression

### ISSUE THREAD

**Issue by jamiehodge** [jcoglan/canopy#10]
Is there a reason why a choice_expression is not an actionable_expression?

**Comment by jcoglan** [comment]
Yes -- actions exist to replace the parser's built-in node construction with your own code, so they don't apply to constructs that essentially emit an already-constructed node.

If you want to use actions with a choice expression, you need to add the action to each branch of the choice.

Does that make sense?

**Comment by jamiehodge** [comment]
Yes, I moved to types as soon as I realised that I didn't have access to labels through actions. Thank you.
