### ISSUE TITLE
Add comment to generated parsers: "Generated from .peg file using Canopy"

### ISSUE THREAD

**Issue by nathanl** [jcoglan/canopy#17]
I just started a project with a generated parser. I didn't know initially that it wasn't hand-written.

It would be very helpful for the generated parser file to start with a comment like:

```ruby    
# Generated from `foo.peg` using Canopy: http://canopy.jcoglan.com/
```

**Comment by jcoglan** [comment]
Thanks for the idea, and sorry it's taken me a while to respond. I've just implemented this, as demonstrated by the project's own grammar parser:

https://github.com/jcoglan/canopy/commit/59deb2673ea66c71c3a31824e81bc8884fe8579b
