### ISSUE TITLE
Question about the license of the generated code

### ISSUE THREAD

**Issue by rfellows** [jcoglan/canopy#21]
First off, I'm pretty impressed with your tool. However, my employer is someone scared off by the GPL license of Canopy itself. But it is unclear to me if the code generated by Canopy is also licensed under GPL or something else.

Could you please clarify this for me?

**Comment by realisation** [comment]
This would be nice to know!

**Comment by tab58** [comment]
I'd like to know this as well. Any insights here @jcoglan ?

**Comment by mirabilos** [comment]
Also needed before I can even consider this.

**Comment by jcoglan** [comment]
I didn't answer this immediately because I was unsure how to respond. Nothing has changed there, and to be very clear about this: **I am not qualified to give legal advice and nothing I say here should be construed as legal advice**. There's no further comment I can make here so I'm closing this issue.

**Comment by mirabilos** [comment]
In this case we’ll have to be careful (because the author _does_ make a statement but _doesn’t_ follow common practice in their grant) and assume GPLv3-or-later, disqualifying this for almost all Java™ projects. I’m off then.

**Comment by jcoglan** [comment]
@mirabilos Are you able to explain this comment further:

> (because the author does make a statement but doesn’t follow common practice in their grant) and assume GPLv3-or-later, disqualifying this for almost all Java™ projects

I understand if you're unable to give further comment but anything you could share that would explain why this cannot be used for Java projects would be useful.

**Comment by mirabilos** [comment]
James Coglan dixit:

>anything you could share that would explain why this cannot be used for
>Java projects would be useful.

Most Java™ projects have components under GPL-incompatible licences.

Almost everything from Sun/Oracle for example has CDDL (GPL-incompatible)
dual-licenced with GPLv2-only with classpath exception, which is
compatible with everything *except* GPLv3+ (or LGPLv3+ if another component
is GPLv2-or-later), and Apache 2 is only compatible with GPLv3 but not
GPLv2, and one is bound to have both of these in most projects.

bye,
//mirabilos (Open Source licencing expert at $dayjob)
-- 
I believe no one can invent an algorithm. One just happens to hit upon it
when God enlightens him. Or only God invents algorithms, we merely copy them.
If you don't believe in God, just consider God as Nature if you won't deny
existence.		-- Coywolf Qi Hunt

**Comment by russells-crockpot** [comment]
Wouldn't the author of canopy choose the license of the outputted code just like they do with license for canopy itself?

**Comment by jcoglan** [comment]
Further to this conversation, I have just shipped v0.4 under the Mozilla Public License, with the intention that generated parsers can be distributed under any terms the user likes. More information here: https://blog.jcoglan.com/2022/04/01/announcing-canopy-0-4/
