### ISSUE TITLE
How to designate which nodes are created? 

### ISSUE THREAD

**Issue by realisation** [jcoglan/canopy#26]
Aha - one should use actions to pass their desired node back to the parent tree.

**Comment by jcoglan** [comment]
You should probably look at the docs for [building parse trees](http://canopy.jcoglan.com/types.html). This describes how to bind functions to grammar rules so that they're executed during matching to override Canopy's default tree-building behaviour.

**Comment by realisation** [comment]
Yea, just figured that out by the time you responded here.

**Comment by realisation** [comment]
Hmm, why would I encounter this error when I try to assign an action onto my program node? 

```
SyntaxError: Line 166: expected [\s], "#", "<-", [a-zA-Z_], "(", "&", "!", '"', "'", "`", "[", ".", "<", "/"
  Program         <- SourceElements %makeProgram
```

Grammar up to that point is as follows

```
  Start <- (__) Program
  Program <- SourceElements %makeProgram (my action) 
  SourceElements <- Statement
  Statement <- ExpressionStatement
  .... so on. is the rest relevant?
```
