### ISSUE TITLE
Question: how to match on end of string? 

### ISSUE THREAD

**Issue by nmorse** [jcoglan/canopy#36]
How can I match on the end of input (or end of input string)?

in .peg file I have this ` end_of_string <-  [$]+ `, but it does not seem to match the 'end of string'.

Is there a better way? (sorry to make an issue,  I did look for the answer in the docs and on stackoverflow, first)

**Comment by jcoglan** [comment]
There isn't an explicit operator for matching the end of the string -- Canopy parsers implicitly match the entire input. If you give the parser some input and the parser doesn't reach the end of the input by following the grammar rules, then it will fail with an error.

**Comment by nmorse** [comment]
@jcoglan Thanks for the feedback. My work-around has been to append a space before parsing, that triggers a different rule and alleviates my need to identify an `end_of_input`.

**Comment by jcoglan** [comment]
Oh, I see what you mean. There is a way to match only if an expression appears at the end of the input, which is to use a negative look-ahead to check there is no character after the expression. So, `expr !.` matches `expr` only at the end of the input.

**Comment by jcoglan** [comment]
(Sorry it took me so long to reply in the first place.)
