### ISSUE TITLE
 Regenerating code from a parse tree?

### ISSUE THREAD

**Issue by sandcobainer** [jcoglan/canopy#41]
Pretty simple, I have generated a parse tree and made a few edits to the leaves of the parse tree within the valid ranges of the grammar. Now I want to regenerate the code from the parse tree. 

Examples of the other generator parsers that have reverse functionality: 
https://github.com/tjvr/nearley-reverse
https://github.com/lark-parser/lark
Is this possible with Canopy? If it's not implemented yet, I'd appreciate help in tackling this. Thanks.

**Comment by jcoglan** [comment]
Canopy does not support this and is not likely to add support for it. It doesn't model a lot of the things you need to make this work reliably, for example understanding precedence and associativity as a first class concept. `nearley-reverse` requires that you add extra encoding functions to make your grammar reversible.

If you need to do this, you should write your own serialisation functions that conform to your grammar.
