### ISSUE TITLE
Java parser throws exceptions like crazy

### ISSUE THREAD

**Issue by mirabilos** [jcoglan/canopy#42]
Taking your `url.peg` and…

    import url.*;
    
    public class UrlTest {
        public static void main(String[] argv) {
                try {
                        URL.parse(argv[0]);
                        System.out.println("parsed ok: " + argv[0]);
                } catch (ParseError e) {
                        System.out.println("parse error (" + e + "): " + argv[0]);
                }
        }
    }

… and calling it as…

    java UrlTest foo

… throws:

    Exception in thread "main" java.lang.StringIndexOutOfBoundsException: begin 0, end 4, length 3
        at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
        at java.base/java.lang.String.substring(String.java:1874)
        at url.Grammar._read_scheme(Grammar.java:135)
    […]

There are *many* unchecked `String.substring()` uses, for starters…

**Comment by jcoglan** [comment]
This looks like it was fixed in https://github.com/jcoglan/canopy/issues/23 -- could you have a look at that thread and see if this is the same issue?

By the way, I'd appreciate you not calling things "crazy" when you find a bug in them :)

**Comment by jcoglan** [comment]
I'm closing this as fixed, per my above comment. While there are a lot of unchecked `substring()` calls in the generated code, the one that's really critical is the one generated by the `chunk_()` function, which allows a match to occur. All other `substring()` calls are used in `TreeNode` construction, which should only happen if the parser has succeeded up to the required string offset. It can only do this if leaf matchers like `"hello"`, `[world]` or `.` have consumed input without overflowing the offset.
