### ISSUE TITLE
Publish new release to npm

### ISSUE THREAD

**Issue by y8** [jcoglan/canopy#48]
Hi! 

Last npm release was published 6 years ago, and quite a few things was fixed since then. Could you please publish new release? 

Thanks for awesome library!

**Comment by jcoglan** [comment]
Hi @y8, opening issues whose sole purpose is to remind a volunteer maintainer that they haven't completed some piece of work, or to tell them they're taking too long to do so, is not helpful, and I'd appreciate it very much if people would stop doing this.

**Comment by jcoglan** [comment]
This should now be fixed as part of the v0.4 release; see https://blog.jcoglan.com/2022/04/01/announcing-canopy-0-4/
