### ISSUE TITLE
`make test` does not work so as the installation instruction

### ISSUE THREAD

**Issue by rbtsv** [jcoglan/canopy#56]
I tired to follow the installation instruction and the step `make test` did not work. So I had to manually copy src to lib
```
rubtsov$ make test
npm test
npm ERR! Missing script: "test"
npm ERR!
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rubtsov/.npm/_logs/2021-11-28T20_35_43_434Z-debug.log
make: *** [test] Error 1
```

**Comment by nmorse** [comment]
probably docs should say $ npm run test

but give that a try

**Comment by jcoglan** [comment]
Could I check what commands you're running to install the package? The `make test` script is intended entirely for development and CI use, not for installation.

**Comment by microwavenby** [comment]
As one cannot use NPM to install canopy currently, trying to follow the instructions in `CONTRIBUTING.md` seems like a reasonable fallback

```bash
git clone git://github.com/jcoglan/canopy.git
cd canopy
npm install
make test
```

 

> ~/canopy > make                                                                                                                                                                                                                                                                                                                                        (main) Sashas-MBP
> npm test
> npm ERR! Missing script: "test"
> npm ERR!
> npm ERR! To see a list of scripts, run:
> npm ERR!   npm run
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/sasha/.npm/_logs/2021-12-28T23_39_51_132Z-debug-0.log
> make: *** [test] Error 1

These steps result in the same error that @rbtsv pasted above.
I wonder if it's related to a change in NPM not finding the `test/javascript/package.json` ? 
(I am not a Node.JS dev, so I cannot surmise why that might be the problem)

I'm on npm@8.3.0 on an Intel Mac running Monterey

```bash
~/canopy > cd test/javascript
~/canopy/test/javascript > npm test
```

 

> test
>
> find . -name '*_test.js' | xargs jstest
>
> node:internal/modules/cjs/loader:936
>   throw err;
>   ^
> 
> Error: Cannot find module '../grammars/sequences'
> Require stack:
> - /Users/sasha/canopy/test/javascript/sequences_test.js
> - /Users/sasha/canopy/node_modules/jstest/bin/jstest
>     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
>     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
>     at Module.require (node:internal/modules/cjs/loader:999:19)
>     at require (node:internal/modules/cjs/helpers:102:18)
>     at Object.<anonymous> (/Users/sasha/canopy/test/javascript/sequences_test.js:3:21)
>     at Module._compile (node:internal/modules/cjs/loader:1095:14)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1147:10)
>     at Module.load (node:internal/modules/cjs/loader:975:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
>     at Module.require (node:internal/modules/cjs/loader:999:19) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/Users/sasha/canopy/test/javascript/sequences_test.js',
>     '/Users/sasha/canopy/node_modules/jstest/bin/jstest'
>   ]
> }
> 
> Node.js v17.0.1

I did finally get `npm test` to work at least by copying `canopy/src` contents to `canopy/lib` (to make `canopy/bin/canopy` able to find `../lib/canopy`) and then running `canopy/bin/canopy` on the grammars in `canopy/test/grammars/*.peg`

**Comment by jcoglan** [comment]
I have just fixed the `make test` task to run the JavaScript tests; this is necessary only as a precondition to bootstrapping the project and not how I'd recommend installing it. I am working on getting a usable release prepared, but in the mean time I'm considering this specific issue resolved.
