### ISSUE TITLE
Pass cross-references / named nodes to actions

### ISSUE THREAD

**Issue by nippur72** [jcoglan/canopy#63]
the doc says that cross-references / named nodes are an easier way to traverse the tree than using the `elements` array, but they are not available within `%actions`. Perhaps they could be passed as an extra argument to the action e.g.:

```js
action(input, start, end, elements, node) {
   // node.Identifier 
}
```
alternatively, the action could receive the current TreeNode as `this`:
```js
action(input, start, end, elements) {
   // this.Identifier 
}
```

**Comment by jcoglan** [comment]
Named child elements are a feature of the tree nodes that Canopy generates by default. `%actions` _replace_ Canopy's default node-building code by running your actions instead, with the same inputs that Canopy's own node constructors get. Supporting this feature would require building a default node like normal, and then passing it to your action functions as an argument. This would remove the performance benefit of skipping default node construction.

If you want this behaviour, you're better off letting Canopy build the tree for you and then converting the entire tree yourself. Actions are intended to reduce work by skipping this conversion step.
