### ISSUE TITLE
Indented parsing

### ISSUE THREAD

**Issue by emilebosch** [jcoglan/canopy#8]
Hi i was wondering if its possible to also do indented parsing with canopy? thanks a lot

**Comment by jcoglan** [comment]
Do you mean parsing, for example, Python function definitions?

**Comment by emilebosch** [comment]
exactly or coffee script

**Comment by jcoglan** [comment]
Languages like that can't be entirely parsed with a tool like Canopy because they aren't context-free. One possible solution is to have a preprocessor that just looks at indentation to add delimiters around blocks of code, and then using a context-free parsing tool to process the result.

**Comment by emilebosch** [comment]
Thanks @jcoglan thats what i'll do !
