### ISSUE TITLE
ParseError with wildcard characters

### ISSUE THREAD

**Issue by TheCrow1213** [jcoglan/canopy#9]
This isn't really a bug/issue. More of a question:

I have a bunch of legal text (first few lines):
```
84R1861 MK-D By: Whitmire S.B. No. 107 A BILL TO BE ENTITLED AN ACT relating to the removal, discipline, or transfer of a public school student. BE IT ENACTED BY THE 
```

Then my grammar:
```
grammar TXBILL

txbill <- .* `A BILL TO BE ENTITLED` .*
```

I'd expect this to capture 'A BILL TO BE ENTITLED' and then everything to the left and right of it, yet I get a parsing error on the last line of the text.
![screen shot 2016-06-27 at 7 25 12 pm](https://cloud.githubusercontent.com/assets/1562516/16399987/ed5b09c4-3c9c-11e6-8901-dd09f30ebc28.png)

For reference, here'e that last line: 
```
If this Act does not receive the vote necessary for immediate effect, this Act takes effect September 1, 2015.
```

I might just be doing something stupid... Any guidance would be super appreciated though :)

**Comment by jcoglan** [comment]
This isn't so much an issue with Canopy per se as with PEG in general. PEGs are greedy, so that first `.*` expression will consume the entire input. Unless your document has recursive structure, I'd recommend using regular expressions to process it.

**Comment by TheCrow1213** [comment]
Ahhh ok, that makes sense. I was wondering if this would be the best tool or not, thanks for the input :)
